<#
.SYNOPSIS
  Publish desktop applications on this workstation as RDP RemoteApps ("seamless" apps).

.DESCRIPTION
  RemoteApp lets an RDP client render a SINGLE application window on the client's own
  desktop instead of a whole remote desktop — the Citrix "published application" model.
  Microsoft ships it as a Remote Desktop Services role on Windows Server; the underlying
  support is present on Windows Pro but no UI exposes it, so the publish list has to be
  written to the registry directly. That is all this script does.

  Allow list:  HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Terminal Server\TSAppAllowList
    fDisabledAllowList (DWORD)  0 = only the applications listed below may be published
                                1 = ANY executable may be published (we do NOT do this)
    Applications\<alias>
      Name                (SZ)     display name shown by the client
      Path                (SZ)     full path to the executable
      ShortPath           (SZ)     8.3 path; some client/server combinations require it
      CommandLineSetting  (DWORD)  0 = no arguments, 1 = any arguments, 2 = RequiredCommandLine only
      RequiredCommandLine (SZ)     the fixed argument string when CommandLineSetting = 2
      IconPath / IconIndex         icon shown in the client's window/taskbar

  This does NOT change whether RDP is enabled, the listening port, or NLA. It does not
  affect ordinary full-desktop RDP sessions in any way: the allow list is consulted only
  on connections that ask for RemoteApp mode.

.NOTES
  Windows Pro permits ONE interactive session. A RemoteApp connection attaches to the
  same session a full-desktop connection would, so you can alternate between them but
  cannot hold both, and connecting will disconnect whoever is at the console.

  The matching .rdp files are generated by the workstation rail
  (GET /workstation/api/remoteapp/<id>.rdp) — see rails/workstation/README.md.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File deploy\install-remoteapp.ps1
  powershell -ExecutionPolicy Bypass -File deploy\install-remoteapp.ps1 -List
  powershell -ExecutionPolicy Bypass -File deploy\install-remoteapp.ps1 -Remove
#>
[CmdletBinding(DefaultParameterSetName = 'Install')]
param(
    # Publish an arbitrary executable instead of the built-in VS Code entry.
    [Parameter(ParameterSetName = 'Install')][string]$Alias,
    [Parameter(ParameterSetName = 'Install')][string]$Path,
    [Parameter(ParameterSetName = 'Install')][string]$DisplayName,

    # Argument policy for the published app. 'any' is the default because an editor with
    # an integrated terminal can already run anything once open, so restricting its
    # command line buys no real containment; use 'none' or -RequiredCommandLine to pin it.
    [Parameter(ParameterSetName = 'Install')][ValidateSet('none', 'any', 'required')]
    [string]$CommandLinePolicy = 'any',
    [Parameter(ParameterSetName = 'Install')][string]$RequiredCommandLine = '',

    [Parameter(ParameterSetName = 'Remove')][switch]$Remove,
    [Parameter(ParameterSetName = 'List')][switch]$List
)

$ErrorActionPreference = 'Stop'

$AllowListKey = 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Terminal Server\TSAppAllowList'
$AppsKey = Join-Path $AllowListKey 'Applications'

# The built-in entry. VS Code installs per-user by default, so resolve it rather than
# assuming Program Files.
$DefaultVSCodePaths = @(
    "$env:LOCALAPPDATA\Programs\Microsoft VS Code\Code.exe",
    "$env:ProgramFiles\Microsoft VS Code\Code.exe",
    "${env:ProgramFiles(x86)}\Microsoft VS Code\Code.exe"
)

function Test-Elevated {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    (New-Object Security.Principal.WindowsPrincipal $id).IsInRole(
        [Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-ShortPath([string]$FullPath) {
    # 8.3 generation can be disabled per-volume, in which case GetFile().ShortPath just
    # returns the long path. Either way the value is usable, so never fail on it.
    try {
        $fso = New-Object -ComObject Scripting.FileSystemObject
        return $fso.GetFile($FullPath).ShortPath
    } catch {
        return $FullPath
    }
}

function Show-Published {
    if (-not (Test-Path $AllowListKey)) { Write-Host 'TSAppAllowList: absent (nothing published).'; return }
    $disabled = (Get-ItemProperty $AllowListKey -Name fDisabledAllowList -ErrorAction SilentlyContinue).fDisabledAllowList
    $mode = if ($null -eq $disabled) { 'unset (defaults to enforced)' }
            elseif ($disabled -eq 1) { '1 = UNRESTRICTED — any executable may be published' }
            else { '0 = enforced (only the entries below)' }
    Write-Host "fDisabledAllowList = $mode"
    if (-not (Test-Path $AppsKey)) { Write-Host 'No published applications.'; return }
    $entries = Get-ChildItem $AppsKey -ErrorAction SilentlyContinue
    if (-not $entries) { Write-Host 'No published applications.'; return }
    Write-Host ''
    foreach ($e in $entries) {
        $p = Get-ItemProperty $e.PSPath
        $exists = Test-Path $p.Path
        Write-Host ("  {0,-14} {1}" -f $e.PSChildName, $p.Name)
        Write-Host ("  {0,-14} {1}{2}" -f '', $p.Path, $(if ($exists) { '' } else { '   [MISSING]' }))
        Write-Host ("  {0,-14} CommandLineSetting={1}" -f '', $p.CommandLineSetting)
        Write-Host ''
    }
    Write-Host "Connect with: remoteapplicationprogram:s:||<alias>"
}

# --- self-elevate ------------------------------------------------------------
# This box auto-elevates for the admin account, so RunAs does not prompt.
if (-not (Test-Elevated)) {
    Write-Host 'Re-launching elevated...'
    $argList = @('-ExecutionPolicy', 'Bypass', '-NoProfile', '-File', "`"$PSCommandPath`"")
    foreach ($kv in $PSBoundParameters.GetEnumerator()) {
        if ($kv.Value -is [switch]) { if ($kv.Value.IsPresent) { $argList += "-$($kv.Key)" } }
        else { $argList += @("-$($kv.Key)", "`"$($kv.Value)`"") }
    }
    $p = Start-Process powershell.exe -ArgumentList $argList -Verb RunAs -Wait -PassThru
    exit $p.ExitCode
}

if ($List) { Show-Published; exit 0 }

if ($Remove) {
    if (Test-Path $AppsKey) {
        Remove-Item $AppsKey -Recurse -Force
        Write-Host 'Removed all published applications.'
    } else {
        Write-Host 'Nothing to remove.'
    }
    if (Test-Path $AllowListKey) {
        Remove-ItemProperty $AllowListKey -Name fDisabledAllowList -ErrorAction SilentlyContinue
    }
    Write-Host 'RemoteApp publishing reverted. Full-desktop RDP is unaffected.'
    exit 0
}

# --- resolve what to publish -------------------------------------------------
if (-not $Alias) {
    $Alias = 'vscode'
    $DisplayName = 'Visual Studio Code'
    $Path = $DefaultVSCodePaths | Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $Path) {
        throw "Visual Studio Code was not found in any of:`n  $($DefaultVSCodePaths -join "`n  ")`nPass -Alias/-Path/-DisplayName to publish something else."
    }
}
if (-not $Path) { throw 'Specify -Path when using -Alias.' }
if (-not (Test-Path $Path)) { throw "Executable not found: $Path" }
$Path = (Resolve-Path $Path).Path
if (-not $DisplayName) { $DisplayName = [IO.Path]::GetFileNameWithoutExtension($Path) }

$cmdSetting = switch ($CommandLinePolicy) { 'none' { 0 } 'any' { 1 } 'required' { 2 } }
if ($CommandLinePolicy -eq 'required' -and -not $RequiredCommandLine) {
    throw "-CommandLinePolicy required needs -RequiredCommandLine."
}

# --- write the allow list ----------------------------------------------------
New-Item -Path $AppsKey -Force | Out-Null

# 0 = enforce the list. Deliberately not 1: an unrestricted list would let any RDP
# principal publish any executable, and we only need the entries below.
Set-ItemProperty -Path $AllowListKey -Name fDisabledAllowList -Value 0 -Type DWord

$key = Join-Path $AppsKey $Alias
New-Item -Path $key -Force | Out-Null
Set-ItemProperty -Path $key -Name 'Name'               -Value $DisplayName -Type String
Set-ItemProperty -Path $key -Name 'Path'               -Value $Path -Type String
Set-ItemProperty -Path $key -Name 'ShortPath'          -Value (Get-ShortPath $Path) -Type String
Set-ItemProperty -Path $key -Name 'CommandLineSetting' -Value $cmdSetting -Type DWord
Set-ItemProperty -Path $key -Name 'RequiredCommandLine' -Value $RequiredCommandLine -Type String
Set-ItemProperty -Path $key -Name 'IconPath'           -Value $Path -Type String
Set-ItemProperty -Path $key -Name 'IconIndex'          -Value 0 -Type DWord

Write-Host ''
Write-Host "Published '$DisplayName' as RemoteApp alias '$Alias'." -ForegroundColor Green
Write-Host "  path                 $Path"
Write-Host "  command line         $CommandLinePolicy"
Write-Host "  allow list           enforced (fDisabledAllowList=0)"
Write-Host ''
Write-Host 'Next: fetch the .rdp from the workstation rail, or connect with an .rdp containing'
Write-Host '  remoteapplicationmode:i:1'
Write-Host "  remoteapplicationprogram:s:||$Alias"
Write-Host '  disableremoteappcapscheck:i:1     (required: this is not an RDS server)'
Write-Host ''
Write-Host 'Reminder: Windows Pro allows one interactive session, so a RemoteApp connection'
Write-Host 'takes over the session rather than adding one.'